---
# tasks file for 2do_parcial

- debug:
    msg: "Tareas del 2do Parcial"

- name: "Crear directorios en /tmp/2do_parcial/"
  file:
     path: "/tmp/2do_parcial/{{ item }}"
     state: directory
     mode: '0775'
     recurse: yes
  with_items:
     - "alumno"
     - "equipo"


- name: "Generar archivo de datos del alumno"
  template:
    src: datos_alumno.txt.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt

- name: "Generar archivo de datos del equipo"
  template:
    src: datos_equipo.txt.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt

- name: "Configurar sudoers para el grupo 2PSupervisores"
  lineinfile:
    path: /etc/sudoers
    state: present
    validate: '/usr/sbin/visudo -cf %s'
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'

